### PR TITLE
Replace Cumulative implementation by state-of-the-art implementation of TimeTabling and OverloadChecking

### LINKED ISSUE #1114: [BUG]Unexpected behavior when using Task with scalar
The following test fails:

```java
@Test(groups = "1s", timeOut = 60000)
public void testScalarAndTaskBug1() {
    int[] coeffs = new int[]{3, -2,-1,-2};
    IntVar[] vars = new IntVar[4];
    vars[0] = model.intVar(8, 9);
    vars[1] = model.intVar(2, 4);
    vars[2] = model.intVar(new int[]{1,2,4,5,6});
    vars[3] = model.intVar(3, 5);
    model.scalar(vars, coeffs, "<=", 1).post();
    IntVar ee = model.intVar(4, 9);
    new Task(vars[3], vars[2], ee);
    model.getSolver().solve();
    Assert.assertEquals(model.getSolver().getSolutionCount(), 0);
}
```
When the `scalar` constraint filters, it first reduces `vars[0]` to `8`, then `vars[1]=4` and `vars[2]={5,6}`.
At this point the task automatically reduces the domain of `vars[3]` to `{3,4}`.
Then the `scalar` constraint keeps on filtering and fix vars[3]` to `4` and passivates itself.
But, with `vars[3]=4` there is no solution anymore to this model and `scalar` is not able to detect it because it does not react on modification during its filtering step.
The combination of task filtering and passivate leds to inconsistency. 

So IMO, the way tasks (or more generally monitors) reduce domains is buggy, because we cannot consider that constraints should be aware of reductions made by monitors during their filtering step.
I'm afraid other constraints will produce the same bug...

### PR DESCRIPTION
**Pull request by ArthurGodet**
Also fixes #1114

### CODE REVIEW

**Comment by cprudhom** [comment]
I change the target branch from `master` to `develop`

File: solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/Event.java
Comment (cprudhom) [inline solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/Event.java:1]: This file could be annotated a little more.

File: solver/src/test/java/org/chocosolver/solver/constraints/checker/Modeler.java [hunk 1]
```diff
@@ -670,7 +670,7 @@ public Model model(int n, int[][] domains, THashMap<int[], IntVar> map, Object p
                 h[i] = vars[i + 3 * k];
             }
             IntVar capa = vars[vars.length - 1];
-            model.cumulative(tasks, h, capa, (boolean)parameters).post();
```
Comment (cprudhom) [inline solver/src/test/java/org/chocosolver/solver/constraints/checker/Modeler.java:673]: Ignoring this parameter should also involve the calling test, right?

File: solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/EventPointSeries.java
Comment (cprudhom) [inline solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/EventPointSeries.java:1]: This file could be annotated a little more.

File: solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/Profile.java
Comment (cprudhom) [inline solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/Profile.java:1]: This file could be annotated a little more.

File: solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/PropagatorCapacity.java
Comment (cprudhom) [inline solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/PropagatorCapacity.java:1]: This file could be annotated a little more.

**Review by cprudhom — COMMENTED** [review]
Apart from the missing comments, everything is OK.

File: solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java [hunk 2]
```diff
@@ -0,0 +1,251 @@
...
+            return ref().arithm(capacity, ">=", 0);
+        }
+        final Task[] keptTasks = new Task[tasksToKeep.size()];
+        final IntVar[] keptHeights = new IntVar[tasksToKeep.size()];
+        for (int i = 0; i < tasksToKeep.size(); ++i) {
+            keptTasks[i] = tasksToKeep.get(i);
+            keptHeights[i] = heightsToKeep.get(i);
+        }
+        if (keptTasks.length == 1) {
+            return ref().arithm(keptHeights[0], "<=", capacity);
```
Comment (jgFages) [inline solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java]: height <= capa OR duration = 0, no ?

**Comment by jgFages** [comment]
The branch needs to be rebased from origin/develop

File: solver/src/test/java/org/chocosolver/solver/constraints/checker/Modeler.java (hunk 1 above)
Comment (ArthurGodet) [reply solver/src/test/java/org/chocosolver/solver/constraints/checker/Modeler.java:673]: What calling test ?

File: solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java (hunk 2 above)
Comment (ArthurGodet) [reply solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java]: Indeed, it should be this formula. Now the question is : is it better to use an OR constraint or directly the CUMULATIVE constraint on the only task ?

Comment (jgFages) [reply solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java]: I would expect the OR to be more efficient

Comment (ArthurGodet) [reply solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java]: I will manage it with PropagatorCapacity as it is doing exactly that (and is working with optional task)

Comment (jgFages) [reply solver/src/main/java/org/chocosolver/solver/constraints/ISchedulingFactory.java]: ok

**Comment by ArthurGodet** [comment]
I had problems with git rebase, so, in order to keep a clean git history, we need to squash this PR whenever it is accepted/merged

File: CHANGES.md [hunk 3]
```diff
@@ -70,23 +70,6 @@ See [milestone 5.0.0](https://github.com/chocoteam/choco-solver/milestone/40)
...
-
-4.10.16 - 12 Sep 2024
--------------------
-
-### Hotfix
-- Fix bug in `IntAffineView` (#1101)
-
-**Full Changelog**: https://github.com/chocoteam/choco-solver/compare/v4.10.15...v4.10.16
-
-
```
Comment (jgFages) [inline CHANGES.md:89]: is this change normal ?

File: solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java [hunk 4]
```diff
@@ -1,100 +0,0 @@
...
-			if(d[i].getLB()>0){
-				slb[i] = s[i].getLB();
-				dlb[i] = d[i].getLB();
-				eub[i] = e[i].getUB();
-				hlb[i] = h[i].getLB();
-				assert eub[i]>slb[i];
-				sor_array[idx++] = i;
-			}
-		}
-		sorter.sort(sor_array,idx,comparator);
```
Comment (jgFages) [inline solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java:76]: Is this logic implemented somewhere else ? 
If not, I would like to keep it, within the new framework

File: CHANGES.md (hunk 3 above)
Comment (ArthurGodet) [reply CHANGES.md:89]: Aren't these changes written twice (hence the deleted lines) ?

File: solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java (hunk 4 above)
Comment (ArthurGodet) [reply solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java:76]: Yes, it is kept in the function energyNaive() of PropagatorCumulative. It is not activated by default (we tested on instances of the MiniZinc challenge with Charles), but it is kept for the cases where it helps.

Comment (ArthurGodet) [reply solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java:76]: However, if you talk about the while loop storing values in slb, hlb, eub arrays, then no it is not kept.
Do you see an interest in keeping it ?

Comment (jgFages) [reply solver/src/main/java/org/chocosolver/solver/constraints/nary/cumulative/NRJCumulFilter.java:76]: Ah great thank you very much I didn't see the energyNaive()

**Review by jgFages — APPROVED** [review]

**Comment by ArthurGodet** [comment]
Important to note : the failing tests do not rely on the cumulative constraint

**Comment by cprudhom** [comment]
Here are some results of the new Cumulative (`new`) in comparison to the current version (`base`) on instances from the last 6 MiniZinc challenges declaring `cumulative` constraints.

## With LCG off
image

The two instances that are faster with `base` than with `new` are :
- `gfd-schedule2_n200f5d50m40k6_10124` : 95s vs 100s 
- `model4_opt_test03` : 106s vs 154s

The difference comes from the usage of the OverloadChecking algorithm which never helps on these instances.

image


## With LCG on

image

The two instances where `base-lcg` is faster than `new-lcg` are:
- `mrcpsp_j30_29_3` : 22s vs 57s
- `mrcpsp_j30_54_2` : 12s vs 23s

I still need to understand the differences but as a recall, `base-lcg` time-based decomposes the cumulative constraint.

image

**Comment by ArthurGodet** [comment]
I confirm that base-lcg is based on decomposition for the cumulative. I wonder if the two instances where base-lcg does better are on a short horizon ? That might explain the performance difference.

**Comment by cprudhom** [comment]
Actually, in the benchmarks, there are 5 instances of mrcpsp_j30, with different results.


Instance | Opt | base-lcg | new-lcg
-- | -- | -- | --
mrcpsp_j30_25_5 | min | 27 - 3s - 995n - P | 27 - 1s - 2470n - P
mrcpsp_j30_29_3 | min | 32 - 22s - 24110n - U | 32 - 57s - 166551n - U 
mrcpsp_j30_33_5 | min | 48 - 52s - 7150n - P | 48 - 5s - 9829n - P
mrcpsp_j30_41_8 | min | 30 - 42s - 5822n - P | 30 - 4s - 7984n - P 
mrcpsp_j30_54_2 | min | 28 - 12s - 9537n - U | 28 - 23s - 75877n - P


**Edit 1** : I added the number of nodes  (XXXn) and the termination (P for proven, U for unproven). 
 Now, it seems that `base-lcg` is able to find solutions exploring fewer nodes, but since the decomposition can be big, it also wastes time propagating (see for instance, `mrcpsp_j30_25_5` or `mrcpsp_j30_33_5`).
This, also, mitigates `mrcpsp_j30_54_2` because `base-lcg` is not able to prove the bound, unlike `new-lcg`.

We can conclude that the decomposition provides better explanations (probably, thanks to additional variables introduced by the decomposition) - which is, as far as I known, not surprising.   
On the other hand, the global version of cumulative provides better propagation performances but suffer from weaker explanations.

Question is: can we live with that? 
<details><summary>My opinion</summary>Yes, we can</details>

**Comment by cprudhom** [comment]
Can we consider this PR as ready to be merged ?

**Comment by ArthurGodet** [comment]
I didn't see your edits. So it seems that mrcpsp_j30_29_3 is the only instance that is better treated by base_lcg, and since the best found solution is not proven to be optimal, I'd say that it is not that important (especially compared to the better results we get wih new_lcg for the other instances). I agree that the explanations of new_lcg seem weaker, but my first impression would be that it is not surprising (even if I can't really explain why).

For me, even if it can still be improved (especially by better detecting when to apply the OverloadChecking or not, to improve performance), I consider that the PR can be merged. Don't forget to **_squash and merge_** the PR as the git history of the branch is awful.
